name: grp_project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  floor: ^1.2.0
  floor_generator: ^1.2.0
  build_runner: ^2.3.0
  encrypted_shared_preferences: ^2.0.0
  sqflite: ^2.0.0+3
  sqflite_common_ffi: ^2.0.0+2
  sqflite_common_ffi_web: ^0.4.3+1
  flutter_material_pickers: ^3.6.0
  path_provider: ^2.0.0
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.0
  floor_generator: ^1.2.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
